# Generated by Django 3.2.9 on 2021-12-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211228_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sscreated',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.topic'),
        ),
    ]
